package id.go.pajak.springmvc.bean;
// Generated Nov 3, 2013 3:58:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa implements java.io.Serializable {


     private String nim;
     private String nama;
     private Date tgllahir;
     private Set kuliahs = new HashSet(0);

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim) {
        this.nim = nim;
    }
    public Mahasiswa(String nim, String nama, Date tgllahir, Set kuliahs) {
       this.nim = nim;
       this.nama = nama;
       this.tgllahir = tgllahir;
       this.kuliahs = kuliahs;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Date getTgllahir() {
        return this.tgllahir;
    }
    
    public void setTgllahir(Date tgllahir) {
        this.tgllahir = tgllahir;
    }
    public Set getKuliahs() {
        return this.kuliahs;
    }
    
    public void setKuliahs(Set kuliahs) {
        this.kuliahs = kuliahs;
    }




}


